- name: Generate Tenant config
  delegate_to: localhost
  vars:
    id: "{{ last_run_time }}"
  block:
    - when: deploy_in_dev
      block:
        - name: Get apps to be deployed in dev
          set_fact:
            apps: "{{ applications | selectattr('tenant', 'equalto', tenant) | selectattr('dev_virtual_address', 'defined') | list }}"

        - debug:
            msg: "{{ apps }}"

        - name: Generate tenant config for dev
          when: apps | length != 0
          copy:
            content: "{{ lookup('template', '{{ root_dir }}/templates/app-dev.json.j2') | to_json(indent=2) }}"
            dest: "{{ conf_dir }}/tenant-{{ tenant }}.json"

    - when: not deploy_in_dev
      block:
        - name: Get apps to be deployed
          set_fact:
            apps: "{{ applications | selectattr('tenant', 'equalto', tenant) | list }}"

        - debug:
            msg: "{{ apps }}"

        - name: Generate tenant config
          copy:
            content: "{{ lookup('template', '{{ root_dir }}/templates/app.json.j2') | to_json(indent=2) }}"
            dest: "{{ conf_dir }}/tenant-{{ tenant }}.json"
