app_sec_policies:
  - name: shopping_site_policy
    all_sigs_actions: ["alarm", "block"]
    threat_campaign: true
    allow_untrusted_bots: false
  - name: info_api_policy
    all_sigs_actions: ["alarm"]
    threat_campaign: false
    allow_untrusted_bots: true
