- name: Generate configuration
  hosts: all
  gather_facts: false
  vars:
    last_run_time: "{{ ansible_date_time.iso8601_basic }}"
    artifact_dir: "{{ root_dir }}/.artifact//{{ inventory_hostname }}"

  tasks:
    - delegate_to: localhost
      block:
        - setup:
            gather_subset:
              - min

        - name: Create .artifact directory
          file:
            path: "{{ artifact_dir }}"
            state: directory

        - name: Make a note of last run time
          copy:
            content: "last_run: {{ last_run_time }}"
            dest: "{{ root_dir }}/.artifact/.metadata"

        - name: Generate firewall policies
          copy:
            content: "{{ lookup('template', '{{ root_dir }}/templates/firewall-policy.json.j2') | to_json(indent=2) }}"
            dest: "{{ artifact_dir }}/firewall-policy.json"

        - name: Generate VS with WAF policy
          block:
            - name: Get policy setting for VS
              set_fact:
                policy: "{{ app_sec_policies | selectattr('name', 'equalto', app_sec_policy) | list | first }}"

            - name: Generate policy
              block:
                - name: Render policy to JSON
                  set_fact:
                    policy_json: "{{ lookup('template', '{{ root_dir }}/templates/app-sec-policy.json.j2') | to_json(indent=2) }}"

                - name: Store policy as artifact
                  copy:
                    content: "{{ policy_json }}"
                    dest: "{{ artifact_dir }}/app-sec-policy.json"

            - name: Generate VS config with WAF policy
              copy:
                content: "{{ lookup('template', '{{ root_dir }}/templates/app.json.j2') | to_json(indent=2) }}"
                dest: "{{ artifact_dir }}/virtual-server.json"
              vars:
                id: "{{ last_run_time }}"
                vs: "{{ virtual_servers[0] }}"
