- name: Use Collections
  hosts: all
  connection: httpapi
  gather_facts: false
  collections:
    - f5networks.f5_bigip

  tasks:
    - name: Remove VS
      bigip_as3_deploy:
        content: "{{ lookup('file', '{{ root_dir }}/.artifact/{{ inventory_hostname }}/virtual-server.json') }}"

    - name: Remove dev VS
      bigip_as3_deploy:
        content: "{{ lookup('file', '{{ root_dir }}/.artifact/{{ inventory_hostname }}/dev/virtual-server.json') }}"

    - name: Remove firewall policies
      bigip_as3_deploy:
        content: "{{ lookup('file', '{{ root_dir }}/.artifact/{{ inventory_hostname }}/firewall-policy.json') }}"
        state: absent
        tenant: Common
