- name: Generate configuration
  hosts: all
  gather_facts: false
  vars:
    last_run_time: "{{ ansible_date_time.iso8601_basic }}"
    artifact_dir: "{{ root_dir }}/.artifact//{{ inventory_hostname }}"
  tasks:
    - delegate_to: localhost
      block:
        - setup:
            gather_subset:
              - min

        - name: Create .artifact directory
          file:
            path: "{{ artifact_dir }}"
            state: directory

        - name: Create dev subdir in .artifact directory
          file:
            path: "{{ artifact_dir }}/dev"
            state: directory

        - name: Make a note of last run time
          copy:
            content: "last_run: {{ last_run_time }}"
            dest: "{{ root_dir }}/.artifact/.metadata"

        - name: Generate firewall policies
          copy:
            content: "{{ lookup('template', '{{ root_dir }}/templates/firewall-policy.json.j2') | to_json(indent=2) }}"
            dest: "{{ artifact_dir }}/firewall-policy.json"

        - name: Generate dev VS with WAF policy
          include_tasks: "{{ root_dir }}/tasks/generate-vs-config.yaml"
          vars:
            conf_dir: "{{ artifact_dir }}/dev"
            id: "{{ last_run_time }}"
            vs: "{{ virtual_servers[0] }}"
            deploy_in_dev: true

        - name: Generate VS with WAF policy
          include_tasks: "{{ root_dir }}/tasks/generate-vs-config.yaml"
          vars:
            conf_dir: "{{ artifact_dir }}"
            id: "{{ last_run_time }}"
            vs: "{{ virtual_servers[0] }}"
