- name: Apply config
  hosts: all
  connection: httpapi
  gather_facts: false
  collections:
    - f5networks.f5_bigip

  tasks:
    - name: Create firewall policies
      bigip_as3_deploy:
        content: "{{ lookup('file', '{{ root_dir }}/.artifact/{{ inventory_hostname }}/firewall-policy.json') }}"

    - name: Get a list of unique tenants defined
      set_fact:
        all_tenants: "{{ applications | map(attribute='tenant') | unique | list }}"

    - name: Create dev VS
      when: stage is defined and stage == "dev"
      loop: "{{ all_tenants }}"
      loop_control:
        loop_var: tenant
      bigip_as3_deploy:
        content: "{{ lookup('file', '{{ root_dir }}/.artifact/{{ inventory_hostname }}/dev/tenant-{{ tenant }}.json') }}"

    - name: Create VS
      when: stage is undefined or (stage is defined and stage != "dev")
      loop: "{{ all_tenants }}"
      loop_control:
        loop_var: tenant
      bigip_as3_deploy:
        content: "{{ lookup('file', '{{ root_dir }}/.artifact/{{ inventory_hostname }}/tenant-{{ tenant }}.json') }}"
