- name: Apply config
  hosts: all
  connection: httpapi
  gather_facts: false
  collections:
    - f5networks.f5_bigip

  tasks:
    - name: Create firewall policies
      bigip_as3_deploy:
        content: "{{ lookup('file', '{{ root_dir }}/.artifact/{{ inventory_hostname }}/firewall-policy.json') }}"

    - when: stage is defined and stage == "dev"
      block:
        - name: Get list of tenants to be deployed in dev
          find:
            paths: "{{ root_dir }}/.artifact/{{ inventory_hostname }}/dev"
            file_type: file
            patterns: "tenant-*"
          register: files_result

        - name: Create dev tenants
          loop: "{{ files_result.files }}"
          loop_control:
            loop_var: as3_json_file
            label: "{{ as3_json_file.path | basename }}"
          bigip_as3_deploy:
            content: "{{ lookup('file', '{{ as3_json_file.path }}') }}"

    - when: stage is not defined or (stage is defined and stage != "dev")
      block:
        - name: Get list of tenants to be deployed
          find:
            paths: "{{ root_dir }}/.artifact/{{ inventory_hostname }}"
            file_type: file
            patterns: "tenant-*"
          register: files_result

        - name: Create tenants
          loop: "{{ files_result.files }}"
          loop_control:
            loop_var: as3_json_file
            label: "{{ as3_json_file.path | basename }}"
          bigip_as3_deploy:
            content: "{{ lookup('file', '{{ as3_json_file.path }}') }}"
