- name: Use Collections
  hosts: all
  connection: httpapi
  gather_facts: false
  collections:
    - f5networks.f5_bigip

  tasks:
    - name: Remove tenants
      loop: "{{ applications | map(attribute='tenant') | unique | list }}"
      loop_control:
        loop_var: tenant_name
      bigip_as3_deploy:
        tenant: "{{ tenant_name }}"
        state: absent

    - name: Remove dev tenants
      loop: "{{ applications | selectattr('dev_virtual_address', 'defined') | map(attribute='tenant') | unique | list }}"
      loop_control:
        loop_var: tenant_name
      bigip_as3_deploy:
        tenant: "{{ tenant_name }}_dev"
        state: absent
