- name: Generate configuration
  hosts: all
  gather_facts: false
  vars:
    id: "{{ ansible_date_time.iso8601_basic }}"
    artifact_dir: "{{ root_dir }}/.artifact/{{ inventory_hostname }}"
    rendered_policies: {}
  tasks:
    - delegate_to: localhost
      block:
        - setup:
            gather_subset:
              - min

        - name: Create .artifact directory
          file:
            path: "{{ artifact_dir }}"
            state: directory

        - name: Create dev subdir in .artifact directory
          file:
            path: "{{ artifact_dir }}/dev"
            state: directory

        - name: Make a note of last run time
          copy:
            content: "last_run: {{ id }}"
            dest: "{{ root_dir }}/.artifact/.metadata"

        - name: Get a list of unique tenants defined
          set_fact:
            all_tenants: "{{ applications | map(attribute='tenant') | unique | list }}"

        - name: Generate dev applications for each tenant
          loop: "{{ all_tenants }}"
          loop_control:
            loop_var: tenant
          include_tasks: "{{ root_dir }}/tasks/generate-tenant-config.yaml"
          vars:
            deploy_in_dev: true

        - name: Generate applications for each tenant
          loop: "{{ all_tenants }}"
          loop_control:
            loop_var: tenant
          include_tasks: "{{ root_dir }}/tasks/generate-tenant-config.yaml"
          vars:
            deploy_in_dev: false
