address_lists:
  local_networks:
    - "192.168.0.0/24"
    - "10.0.0.0/24"
  client:
    - "123.4.5.6/32"
  public:
    - "0.0.0.0/0"
  server:
    - "192.168.0.78"

port_lists:
  httpPort:
    - 80
  ftpPorts:
    - 20
    - 21

firewall_policies_as3:
  - name: "f5_bigip_http_policy"
    rules:
      - name: rule-1
        description: Allow clients to access HTTP VS
        protocol: tcp
        source:
          address_lists:
            - public
        destination:
          address_lists:
            - server
          port_lists:
            - httpPort
        action: accept
      - name: rule-2
        description: Deny all other traffic
        action: drop
  - name: "f5_bigip_ftp_policy"
    rules:
      - name: rule-1
        description: Allow internal clients access to FTP VS
        protocol: tcp
        source:
          address_lists:
            - local_networks
            - client
        destination:
          address_lists:
            - server
          port_lists:
            - ftpPorts
        action: accept
      - name: rule-2
        description: Deny all other traffic
        action: drop
