name: Generate artifacts
on:
  push:
    branches-ignore:
      - master
jobs:
  generate-artifacts:
    runs-on: self-hosted
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Generate artifact
        run: |
          make generate
      - uses: actions/upload-artifact@v3
        with:
          name: as3-config
          path: .artifact/
      - uses: 8BitJonny/gh-get-current-pr@2.2.0
        id: pr-check
      - run: 'echo "Is commit in PR: ${{ steps.pr-check.outputs.found }}"'
      - name: Trigger pr-workflow
        if: steps.pr-check.outputs.found
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.REPO_DISPATCH_PAT }}
          event-type: run-pr-workflow
          client-payload: '{"run_id": ${{ github.run_id }}}'
