name: Run PR workflow
on:
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  test-in-dev:
    runs-on: self-hosted
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - uses: dawidd6/action-download-artifact@v2
        with:
          workflow: generate-artifacts.yml
          pr: ${{ github.event.pull_request.number }}
          name: as3-config
          path: .artifact/
      - name: Apply configuration in dev
        run: |
          make apply-in-dev
      - name: Run test in dev
        run: |
          make test-in-dev
