name: Run tests
on:
  workflow_dispatch:
  repository_dispatch:
    types: [run-test]
jobs:
  test:
    runs-on: self-hosted
    steps:
      - name: Set commit status as pending
        uses: myrotvorets/set-commit-status-action@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          sha: ${{ github.event.client_payload.sha }}
          status: pending
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Run test target
        id: run-test-target
        run: |
          set -e
          set -o pipefail

          make test | tee test-output.txt

          echo 'TEST_OUTPUT<<EOF' >> $GITHUB_OUTPUT
          cat test-output.txt >> $GITHUB_OUTPUT
          echo 'EOF' >> $GITHUB_OUTPUT

      - name: Create GitHub issue if test failed
        if: failure()
        uses: JasonEtco/create-an-issue@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TEST_OUTPUT: ${{ steps.run-test-target.outputs.TEST_OUTPUT }}

      - name: Set final commit status
        if: always()
        uses: myrotvorets/set-commit-status-action@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          sha: ${{ github.event.client_payload.sha }}
          status: ${{ job.status }}
