name: Test
on:
  workflow_dispatch:
  repository_dispatch:
    types: [run-test]
jobs:
  run-tests:
    runs-on: self-hosted
    steps:
      - name: Debug event name
        run: |
          echo ${{ github.event_name }}
          echo "${{ toJson(github) }}"
      - name: Set SHA value if triggered by workflow_dispatch
        if: ${{ github.event_name == 'workflow_dispatch'}}
        run: |
          echo "USE_SHA=${{ github.sha }}" >> "$GITHUB_ENV"
      - name: Set SHA value if triggered by repository_dispatch
        if: ${{ github.event_name == 'repository_dispatch'}}
        run: |
          echo "USE_SHA=${{ github.event.client_payload.sha }}" >> "$GITHUB_ENV"
      - name: Set commit status as pending
        uses: myrotvorets/set-commit-status-action@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          sha: ${{ env.USE_SHA }}
          status: pending
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Run make test
        id: run-test
        run: |
          set -o pipefail
          make test 2>&1 | tee test-output.txt
      - name: Extract test results to be published to Github Issue
        if: steps.run-test.outcome == 'failure'
        id: extract-results
        run: |
          echo 'TEST_OUTPUT<<EOF' >> $GITHUB_OUTPUT
          cat test-output.txt >> $GITHUB_OUTPUT
          echo 'EOF' >> $GITHUB_OUTPUT
      - name: Create GitHub issue if test failed
        if: steps.run-test.outcome == 'failure'
        uses: JasonEtco/create-an-issue@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TEST_OUTPUT: ${{ steps.extract-results.outputs.TEST_OUTPUT }}
      - name: Set final commit status
        if: always()
        uses: myrotvorets/set-commit-status-action@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          sha: ${{ env.USE_SHA }}
          status: ${{ job.status }}
